import { NextResponse } from "next/server";
import { currentMember } from "@/lib/member-session";
import { categoryAccess } from "@/lib/category-access";
import { getOwnQuotation,getSeedRequest,supplierCanAccess,supplierCanQuote,supplierCanReadOwnHistory,supplierQuotationView,supplierRequestView,upsertQuotation,validateQuotation,SeedConflictError } from "@/lib/seed-trading";
import { readJsonBody,RequestBodyError } from "@/lib/request-body";
const reply=(body:object,status=200)=>NextResponse.json(body,{status,headers:{"Cache-Control":"private, no-store"}}); type C={params:Promise<{requestId:string}>};
async function member(){const m=await currentMember();return m&&!m.mustChangePassword&&categoryAccess(m)?.id==="agriculture"?m:null;}
export async function GET(_r:Request,{params}:C){const m=await member();if(!m)return reply({error:"Approved Agriculture membership required."},403);const {requestId}=await params;const req=await getSeedRequest(requestId);if(!req)return reply({error:"Request not found or unavailable."},404);const owner=String(req.ownerId)===String(m.id);const q=owner?null:await getOwnQuotation(requestId,m.id);if(!supplierCanAccess(req,m)&&!supplierCanReadOwnHistory(req,m,q))return reply({error:"Request not found or unavailable."},404);return reply({request:owner?req:supplierRequestView(req,q||undefined),quotation:owner?null:await supplierQuotationView(req,q)});}
export async function POST(request:Request,{params}:C){const m=await member();if(!m)return reply({error:"Approved Agriculture membership required."},403);if(request.headers.get("origin")&&request.headers.get("origin")!==new URL(request.url).origin)return reply({error:"Invalid request origin."},403);const {requestId}=await params;const req=await getSeedRequest(requestId);if(!req||!supplierCanQuote(req,m))return reply({error:"You are not eligible to quote this request."},403);try{const values=validateQuotation(await readJsonBody(request),req);return reply({quotation:await upsertQuotation(req,m,values)},201);}catch(e){if(e instanceof RequestBodyError)return reply({error:e.message},e.status);if(e instanceof SeedConflictError)return reply({error:e.message},409);return reply({error:e instanceof Error?e.message:"Invalid quotation."},400);}}
