// Server component (force-dynamic): Date.now() is per-request on the server
// (correct for pilot-check timestamps). The react-hooks/purity rule is a false
// positive for server components. Inline-SQL row types are loosely typed.
/* eslint-disable react-hooks/purity, @typescript-eslint/no-explicit-any */
import { redirect } from "next/navigation";
import { env } from "@/lib/runtime-env";
import { requireChatGPTUser } from "@/app/chatgpt-auth";
import { isConfiguredAdmin } from "@/lib/member-data";
import { reportDb } from "@/lib/report-store";
import { ReportShell } from "@/components/report-shell";
import { PilotConsole } from "@/components/pilot-console";
export const dynamic="force-dynamic";
const defaults=[['auth','Member credentials and latest-login session rule','Access'],['category','Agriculture and Other category isolation','Seller search'],['shared-seller','Two pilot companies report the same seller','Reports'],['approval','Pending seller becomes searchable only after approval','Reports'],['documents','Members cannot open another company’s documents','Documents'],['changes','Approved report change returns for admin approval','Reports'],['resolution','Resolution month/year and ongoing workflow','Disputes'],['governance','Correction, suppression and deletion workflows','Governance'],['export','Only administrator can export CSV','Security'],['notifications','Member and administrator notifications','Notifications']];
export default async function Page(){const user=await requireChatGPTUser('/admin/pilot');if(!isConfiguredAdmin(user.email))redirect('/join');const db=reportDb(),now=Date.now();for(const [key,label,area] of defaults)await db.prepare("INSERT INTO pilot_checks(id,check_key,label,area,status,updated_at) VALUES(?,?,?,?, 'not_tested',?) ON CONFLICT (check_key) DO NOTHING").bind(crypto.randomUUID(),key,label,area,now).run();const [issues,checks,members,health]=await Promise.all([db.prepare("SELECT i.*,m.company_name,m.login_id,CASE WHEN i.status='open' THEN 0 WHEN i.status='in_progress' THEN 1 WHEN i.status='ready_for_retest' THEN 2 ELSE 3 END status_rank FROM pilot_issues i JOIN members m ON m.id=i.member_id ORDER BY status_rank,i.updated_at DESC LIMIT 100").all<any>(),db.prepare("SELECT * FROM pilot_checks ORDER BY area,label").all<any>(),db.prepare("SELECT m.id,m.company_name,m.login_id,m.is_pilot,count(r.id) report_count FROM members m LEFT JOIN seller_reports r ON r.member_id=m.id WHERE m.status IN ('approved','deactivated') GROUP BY m.id,m.company_name,m.login_id,m.is_pilot ORDER BY m.is_pilot DESC,m.company_name LIMIT 200").all<any>(),db.prepare("SELECT (SELECT count(*) FROM pilot_issues WHERE status<>'closed') open_issues,(SELECT count(*) FROM seller_reports r JOIN members m ON m.id=r.member_id WHERE m.is_pilot=1) pilot_reports,(SELECT count(*) FROM seller_reports WHERE status='pending')+(SELECT count(*) FROM dispute_resolution_requests WHERE status='pending')+(SELECT count(*) FROM members WHERE status='pending') pending_work").first<any>()]);return <ReportShell admin title="Pilot Center" description="Run controlled acceptance testing without mixing pilot data into the live seller network."><PilotConsole issues={issues.results} checks={checks.results} members={members.results} health={{database:true,fileStorage:Boolean(env.REPORT_FILES),openIssues:Number(health?.open_issues||0),pilotReports:Number(health?.pilot_reports||0),pendingWork:Number(health?.pending_work||0)}}/></ReportShell>}
