import { readFormBody } from "@/lib/request-body";
import { NextResponse } from "next/server";
import { env } from "@/lib/runtime-env";
import { reportDb,reportMember } from "@/lib/report-store";
import { redactIdentifiers,amountPaise } from "@/lib/report-validation";
import { flagRepeatedUpload } from "@/lib/security";
import { notifyAdmin } from "@/lib/notifications";
import { operationGuard } from "@/lib/operation-guard";
const reply=(data:object,status=200)=>NextResponse.json(data,{status,headers:{"Cache-Control":"no-store"}});
export async function POST(request:Request){
 
 const member=await reportMember();if(!member)return reply({error:"Approved membership required."},403);
 let uploaded:string|null=null;
 try{
  const form=await readFormBody(request),reportId=String(form.get("reportId")||""),resolvedOn=String(form.get("resolvedOn")||""),description=redactIdentifiers(String(form.get("description")||"").trim()),resolvedAmount=String(form.get("resolvedAmount")||"").trim().replace(/,/g,""),resolvedUnit=String(form.get("resolvedUnit")||"rupees")||"rupees",resolvedAmountPaise=amountPaise(resolvedAmount,resolvedUnit);
  const today=new Date().toISOString().slice(0,10),parsedDate=new Date(`${resolvedOn}T00:00:00Z`);if(!/^\d{4}-\d{2}-\d{2}$/.test(resolvedOn)||Number.isNaN(parsedDate.valueOf())||parsedDate.toISOString().slice(0,10)!==resolvedOn||resolvedOn>today||description.length<10||description.length>2000)return reply({error:"Enter a valid resolution date and factual description."},400);
  const db=reportDb();const report=await db.prepare("SELECT id,amount_paise,resolved_amount_paise FROM seller_reports WHERE id=? AND member_id=? AND category=? AND status='approved' AND dispute=1 AND dispute_resolved=0").bind(reportId,member.id,member.category).first<{id:string;amount_paise:number;resolved_amount_paise:number}>();if(!report)return reply({error:"This dispute cannot be marked resolved."},409);if(!Number.isSafeInteger(resolvedAmountPaise)||resolvedAmountPaise<=0||resolvedAmountPaise>Number(report.amount_paise||0)-Number(report.resolved_amount_paise||0))return reply({error:"Resolved amount must be positive and cannot exceed the remaining disputed amount."},400);
  if(await db.prepare("SELECT id FROM dispute_resolution_requests WHERE report_id=? AND status='pending'").bind(reportId).first())return reply({error:"A resolution request is already awaiting review."},409);
  const file=form.get("document"),validFile=file instanceof File&&file.size>0?file:null;if(validFile&&validFile.size>1.5*1024*1024){await flagRepeatedUpload(request,member.id,"Repeated oversized resolution evidence uploads");return reply({error:"The optional document must be 1.5 MB or smaller."},400);}
  let document:{id:string;key:string;mime:string;name:string;size:number}|null=null;
  if(validFile){const bytes=new Uint8Array(await validFile.slice(0,12).arrayBuffer());const mime=bytes[0]===0x25&&bytes[1]===0x50&&bytes[2]===0x44&&bytes[3]===0x46&&bytes[4]===0x2d?"application/pdf":bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff?"image/jpeg":bytes.slice(0,8).join(",")==="137,80,78,71,13,10,26,10"?"image/png":"";if(!mime){await flagRepeatedUpload(request,member.id,"Repeated invalid resolution evidence file types");return reply({error:"Only PDF, JPG and PNG documents are accepted."},400);}const id=crypto.randomUUID(),key=`resolutions/${reportId}/${id}`;await env.REPORT_FILES.put(key,validFile.stream(),{httpMetadata:{contentType:mime}});uploaded=key;document={id,key,mime,name:redactIdentifiers(validFile.name).slice(0,150),size:validFile.size};}
  const id=crypto.randomUUID(),now=Date.now();const guard=operationGuard("EXISTS(SELECT 1 FROM seller_reports WHERE id=? AND member_id=? AND status='approved' AND dispute=1 AND dispute_resolved=0) AND NOT EXISTS(SELECT 1 FROM dispute_resolution_requests WHERE report_id=? AND status='pending') AND NOT EXISTS(SELECT 1 FROM seller_reports WHERE revision_of=? AND status='pending')",[reportId,member.id,reportId,reportId]);const statements=[guard.check,db.prepare("INSERT INTO dispute_resolution_requests(id,report_id,member_id,resolved_on,resolved_amount_paise,description,status,created_at) VALUES(?,?,?,?,?,?,'pending',?)").bind(id,reportId,member.id,resolvedOn,resolvedAmountPaise,description,now)];if(document)statements.push(db.prepare("INSERT INTO dispute_resolution_documents(id,request_id,object_key,name,mime,size) VALUES(?,?,?,?,?,?)").bind(document.id,id,document.key,document.name,document.mime,document.size));statements.push(db.prepare("INSERT INTO report_audit(id,report_id,actor,action,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),reportId,`member:${member.id}`,"resolution_requested",now));statements.push(guard.release);await db.batch(statements);await notifyAdmin({type:"resolution_request",title:"New dispute resolution request",message:"A member submitted a dispute resolution for review.",href:"/admin/resolutions"});return reply({id},201);
 }catch{if(uploaded)await env.REPORT_FILES.delete(uploaded).catch(()=>{});return reply({error:"Unable to submit resolution request. Please try again."},500);}
}
