import { LegalPage } from "@/components/legal-page";
export default function Privacy(){return <LegalPage title="Privacy Policy" path="/privacy" effective="12 September 2026">
 <section><h2>1. Who operates the platform</h2><p>Sellers Trust Network is operated by Meet Patel, an individual, from 2nd Floor, Dhanlaxmi House, opposite Commerce & Arts College, NH-48, Motipura, Himatnagar, Sabarkantha, Gujarat 383001, India. Privacy and grievance enquiries may be sent to <a className="underline" href="mailto:meetpatel.hmt@gmail.com">meetpatel.hmt@gmail.com</a>.</p></section>
 <section><h2>2. Information we collect</h2><ul><li>Company identity, GSTIN, address, category and authorised representative contact details.</li><li>Member ID, encrypted password credentials, sessions, login attempts and security records.</li><li>Seller reports, ratings, dispute and legal-proceeding information, factual summaries and supporting documents.</li><li>Technical records such as timestamps, network identifiers, audit activity and essential service logs.</li><li>Correction, grievance, account-deletion and support communications.</li></ul><p>Do not upload Aadhaar numbers, banking passwords, card information, unrelated personal documents or information you are not legally permitted to provide.</p></section>
 <section><h2>3. Why we process information</h2><p>We use information to verify membership, operate category-restricted GSTIN searches, review and publish factual commercial reports, administer disputes and corrections, secure accounts, investigate misuse, maintain an audit trail, communicate essential service notices and comply with law. We do not use seller information to guarantee creditworthiness.</p></section>
 <section><h2>4. Disclosure and access</h2><p>Approved members see only approved records within their assigned category and only after an exact GSTIN search. GSTINs are masked in results. Supporting evidence is restricted to the submitting member and administrators. Approved dispute reports may identify the reporting company. Service providers may process data for hosting, database, storage, security and future communications, including approved cloud processing outside India where lawful and protected by appropriate arrangements.</p></section>
 <section><h2>5. Retention</h2><ul><li>Rejected membership applications and rejected reports: ordinarily 30 days after rejection, subject to legal holds and backup cycles.</li><li>Approved reports, their evidence and audit records: retained as part of the commercial-history ledger while the platform’s lawful purpose continues.</li><li>Deactivated accounts: retained until an administrator approves deletion or continued retention is legally necessary.</li><li>In-app notifications: 10 days.</li><li>Security records and backups: retained for security, integrity, recovery and legal needs, then deleted or overwritten when no longer required.</li></ul><p>Backups are not used to restore a deleted account except for disaster recovery, security investigation or legal compliance.</p></section>
 <section><h2>6. Your choices and requests</h2><p>You may request access, correction, account closure or deletion by emailing the grievance contact. Approved historical reports may be retained after account closure, but the closed member’s identity will be removed from member-facing attribution where reasonably possible. A seller may request correction or removal by providing its GST certificate and details of the challenged record. While reviewed, the record may be labelled “under review.” We aim to respond within 7–15 working days.</p></section>
 <section><h2>7. Security, cookies and analytics</h2><p>We use access controls, password hashing, single-active-session controls, rate limits and audit logs. No system is completely secure. Essential cookies are used for authentication and security. Analytics may be introduced to understand service performance. Advertising or marketing cookies will not be introduced without updating this notice and obtaining any consent required by law.</p></section>
 <section><h2>8. Changes and complaints</h2><p>Material changes will ordinarily be notified 15 days in advance. Meet Patel is the Grievance Officer and Owner. Contact <a className="underline" href="mailto:meetpatel.hmt@gmail.com">meetpatel.hmt@gmail.com</a> or write to the address above. You may also pursue remedies available under applicable Indian law.</p></section>
 </LegalPage>;}
