import type { Metadata } from "next";
import { headers } from "next/headers";
import "./globals.css";
import { LegalFooter } from "@/components/legal-footer";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { BackToTop } from "@/components/back-to-top";

export const metadata: Metadata = {
  metadataBase: new URL("https://sellerstrustnetwork.com"),
  title: {
    default: "Sellers Trust Network — Verified seller intelligence for Indian businesses",
    template: "%s · Sellers Trust Network",
  },
  description: "A private, category-controlled company verification network. Search verified seller reports by GSTIN, file structured dispute reports, and resolve disputes transparently.",
  keywords: ["seller verification", "GSTIN search", "B2B due diligence", "dispute resolution", "company verification", "India business", "seller trust"],
  authors: [{ name: "Meet Patel" }],
  creator: "Meet Patel",
  publisher: "Meet Patel",
  openGraph: {
    title: "Sellers Trust Network",
    description: "Private, category-controlled company verification network for Indian businesses.",
    type: "website",
    locale: "en_IN",
    siteName: "Sellers Trust Network",
  },
  twitter: {
    card: "summary",
    title: "Sellers Trust Network",
    description: "Private, category-controlled company verification network for Indian businesses.",
  },
  robots: { index: true, follow: true },
  manifest: "/site.webmanifest",
  applicationName: "Sellers Trust Network",
  appleWebApp: {
    capable: true,
    title: "Sellers Trust Network",
    statusBarStyle: "default",
  },
  formatDetection: { telephone: false, email: false, address: false },
  icons: {
    icon: [
      { url: "/sellers-trust-network-mark.png", sizes: "192x192" },
      { url: "/sellers-trust-network-mark.png", sizes: "512x512" },
    ],
    shortcut: "/sellers-trust-network-mark.png",
    apple: "/sellers-trust-network-mark.png",
  },
};

// JSON-LD structured data for search engines (Organization + WebSite schema).
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "Organization",
      "@id": "https://sellerstrustnetwork.com/#organization",
      name: "Sellers Trust Network",
      url: "https://sellerstrustnetwork.com",
      founder: { "@type": "Person", name: "Meet Patel" },
      email: "meetpatel.hmt@gmail.com",
      address: {
        "@type": "PostalAddress",
        streetAddress: "2nd Floor, Dhanlaxmi House, opposite Commerce & Arts College, NH-48, Motipura",
        addressLocality: "Himatnagar",
        addressRegion: "Gujarat",
        postalCode: "383001",
        addressCountry: "IN",
      },
      description: "Private, category-controlled company verification network for Indian businesses.",
    },
    {
      "@type": "WebSite",
      "@id": "https://sellerstrustnetwork.com/#website",
      url: "https://sellerstrustnetwork.com",
      name: "Sellers Trust Network",
      publisher: { "@id": "https://sellerstrustnetwork.com/#organization" },
      potentialAction: {
        "@type": "SearchAction",
        target: "https://sellerstrustnetwork.com/login",
        "query-input": "required name=search_string",
      },
    },
  ],
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Read the per-request nonce generated by proxy. Apply it to inline
  // scripts (JSON-LD) so the strict CSP (script-src 'nonce-...') allows them.
  const nonce = (await headers()).get("x-csp-nonce") ?? undefined;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          type="application/ld+json"
          nonce={nonce}
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
        <meta name="theme-color" content="#15388c" />
        <meta name="msapplication-TileColor" content="#15388c" />
      </head>
      <body className="antialiased">
        {/* Skip-to-content link for keyboard / screen-reader users */}
        <a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-lg focus:bg-[#15388c] focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-white focus:shadow-lg">
          Skip to content
        </a>
        <ThemeProvider nonce={nonce}>
          <div className="flex min-h-screen flex-col">
            <div id="main-content" className="flex-1">{children}</div>
            <ThemeToggle/>
            <BackToTop/>
            <LegalFooter/>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
