"use client";
import { useEffect, useState } from "react";
import { readJsonResponse } from "@/lib/client-response";
type Correction={id:string;request_type:string;requester_name:string;requester_email:string;reason:string;status:string;firm_name:string;target_report_id:string|null;created_at:number};
type Deletion={id:string;member_id:number;company_name:string;reason:string;status:string;created_at:number};
type Scheduled={type:"member"|"report";id:string;label:string;delete_on:number;held:boolean};
type Hold={id:string;target_type:string;target_id:string;reason:string;created_at:number};
export function GovernanceConsole({corrections,deletions,scheduled,holds}:{corrections:Correction[];deletions:Deletion[];scheduled:Scheduled[];holds:Hold[]}){const [error,setError]=useState(""),[busy,setBusy]=useState(false),[hasDue,setHasDue]=useState(false);
// "Delete due records" visibility depends on the current time, which must be
// evaluated client-side after mount to avoid a hydration mismatch.
// eslint-disable-next-line react-hooks/set-state-in-effect
useEffect(()=>{setHasDue(scheduled.some(item=>item.delete_on<=Date.now()&&!item.held));},[scheduled]);
async function send(url:string,body:object,confirmation?:string){if(confirmation&&!confirm(confirmation))return;setBusy(true);setError("");try{const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await readJsonResponse<{error?:string}>(response);if(!response.ok)throw new Error(data.error||"Unable to save.");window.location.reload();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save.");setBusy(false);}}
 return <div className="space-y-5">{error&&<p role="alert" className="rounded-2xl bg-rose-50 p-4 text-rose-700">{error}</p>}
 <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><h2 className="text-lg font-semibold text-slate-900">Record seller correction/removal request</h2><p className="mt-1.5 text-[13px] text-slate-500">Use this after receiving the seller’s email and verifying its GST certificate.</p><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));send("/api/admin/correction",{...values,action:"create",gstCertificateVerified:values.gstCertificateVerified==="yes"});}}><Input name="gstin" label="Seller GSTIN"/><label className="text-[13px] font-medium text-slate-700">Category<select name="category" className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-[14px]"><option value="agriculture">Agriculture</option><option value="other">Other</option></select></label><Input name="requesterName" label="Requester name"/><Input name="requesterEmail" label="Requester email" type="email"/><label className="text-[13px] font-medium text-slate-700">Request type<select name="requestType" className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-[14px]"><option value="correction">Identity correction</option><option value="removal">Report removal</option></select></label><Input name="targetReportId" label="Target report ID (for removal)" required={false}/><Input name="firmName" label="Corrected firm name" required={false}/><Input name="taluka" label="Corrected taluka" required={false}/><Input name="district" label="Corrected district" required={false}/><Input name="state" label="Corrected state" required={false}/><label className="flex items-center gap-3 text-[13px] text-slate-700"><input type="checkbox" name="gstCertificateVerified" value="yes" required className="size-4 rounded"/>GST certificate received and verified</label><label className="text-[13px] font-medium text-slate-700 sm:col-span-2">Reason and evidence summary<textarea name="reason" required minLength={5} className="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-[14px]"/></label><button disabled={busy} className="w-fit rounded-xl bg-[#15388c] px-5 py-2.5 text-[13px] font-semibold text-white">Record request</button></form></section>
 <Section title="Correction and removal cases" empty="No correction requests recorded.">{corrections.map(item=><article key={item.id} className="border-b py-5 last:border-0"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{item.firm_name} · {item.request_type}</h3><p className="text-sm text-slate-500">{item.requester_name} · {item.requester_email} · {new Date(item.created_at).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}</p></div><strong className="capitalize">{item.status}</strong></div><p className="mt-3 text-slate-700">{item.reason}</p>{item.status==="pending"&&<form className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));send("/api/admin/correction",{...values,id:item.id,action:"decide"},"Save this final correction decision?");}}><select name="decision" className="h-11 rounded-lg border bg-white px-3"><option value="corrected">Approve correction</option><option value="suppressed">Suppress target report</option><option value="rejected">Reject request</option></select><input name="notes" required minLength={2} placeholder="Decision reason" className="h-11 rounded-lg border px-3"/><button disabled={busy} className="rounded-lg bg-emerald-800 px-4 text-white">Save decision</button></form>}</article>)}</Section>
 <Section title="Account-deletion requests" empty="No account-deletion requests.">{deletions.map(item=><article key={item.id} className="border-b py-5 last:border-0"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{item.company_name} · Member {item.member_id}</h3><p className="mt-1 text-slate-600">{item.reason}</p></div><strong className="capitalize">{item.status}</strong></div>{item.status==="pending"&&<form className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));send("/api/admin/account-deletion",{...values,id:item.id},"Save this account-deletion decision?");}}><select name="status" className="h-11 rounded-lg border bg-white px-3"><option value="approved">Approve and close account</option><option value="rejected">Reject request</option></select><input name="notes" required minLength={2} placeholder="Decision reason" className="h-11 rounded-lg border px-3"/><button disabled={busy} className="rounded-lg bg-emerald-800 px-4 text-white">Save decision</button></form>}</article>)}</Section>
 <Section title="Scheduled deletion" empty="No records are currently scheduled for deletion."><p className="mb-4 text-sm text-slate-500">Records appear here during the seven-day warning period. Active legal holds prevent deletion.</p>{scheduled.map(item=><article key={`${item.type}-${item.id}`} className="flex flex-wrap items-center justify-between gap-4 border-b py-4 last:border-0"><div><p className="font-semibold">{item.label}</p><p className="text-sm text-slate-500">Delete on {new Date(item.delete_on).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})} · {item.held?"Legal hold active":item.type}</p></div>{!item.held&&<button disabled={busy} onClick={()=>{const reason=prompt("Reason for legal hold");if(reason)send("/api/admin/legal-hold",{targetType:item.type,targetId:item.id,reason});}} className="rounded-lg border px-4 py-2 text-sm font-semibold">Place legal hold</button>}</article>)}{hasDue&&<button disabled={busy} onClick={()=>send("/api/admin/cleanup",{},"Permanently delete all due records and their documents?")} className="mt-5 rounded-lg bg-rose-700 px-5 py-3 font-semibold text-white">Delete due records</button>}</Section>
 <Section title="Active legal holds" empty="No active legal holds.">{holds.map(item=><article key={item.id} className="flex flex-wrap items-center justify-between gap-4 border-b py-4 last:border-0"><div><p className="font-semibold capitalize">{item.target_type} · {item.target_id}</p><p className="text-sm text-slate-600">{item.reason}</p></div><button disabled={busy} onClick={()=>send("/api/admin/legal-hold",{action:"release",targetType:item.target_type,targetId:item.target_id,reason:"Release approved"},"Release this legal hold?")} className="rounded-lg border px-4 py-2 text-sm font-semibold">Release hold</button></article>)}</Section>
 </div>;}
function Input({name,label,type="text",required=true}:{name:string;label:string;type?:string;required?:boolean}){return <label className="text-[13px] font-medium text-slate-700">{label}<input name={name} type={type} required={required} className="mt-1.5 h-11 w-full rounded-xl border border-slate-200 px-3 text-[14px]"/></label>;}
function Section({title,empty,children}:{title:string;empty:string;children:React.ReactNode[]|React.ReactNode}){const count=Array.isArray(children)?children.length:1;return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-7"><h2 className="text-lg font-semibold text-slate-900">{title}</h2>{count? <div className="mt-4">{children}</div>:<p className="mt-4 text-[14px] text-slate-500">{empty}</p>}</section>;}
