/* Inline-SQL row types are loosely typed (any) for brevity on dense query pages. */
/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useState } from "react";
import { readJsonResponse } from "@/lib/client-response";
type Issue={id:string;company_name:string;login_id:string|null;issue_type:string;page_url:string;description:string;status:string;admin_notes:string|null;created_at:number;screenshot_name:string|null};
type Check={id:string;check_key:string;label:string;area:string;status:string;notes:string|null};
type PilotMember={id:number;company_name:string;login_id:string|null;is_pilot:number;report_count:number};
export function PilotConsole({issues,checks,members,health}:{issues:Issue[];checks:Check[];members:PilotMember[];health:{database:boolean;fileStorage:boolean;openIssues:number;pilotReports:number;pendingWork:number}}){const [busy,setBusy]=useState(false),[error,setError]=useState(""),[preview,setPreview]=useState<{members:number;reports:number;documents:number;issues:number}|null>(null);async function send(body:object){setBusy(true);setError("");try{const response=await fetch("/api/admin/pilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await readJsonResponse<any>(response);if(!response.ok)throw new Error(data.error||"Unable to update pilot testing.");if(data.preview){setPreview(data.preview);setBusy(false);}else window.location.reload();}catch(cause){setError(cause instanceof Error?cause.message:"Unable to update pilot testing.");setBusy(false);}}
 return <div className="space-y-8">{error&&<p role="alert" className="rounded-xl bg-rose-50 p-4 text-rose-700">{error}</p>}<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Database",health.database?"Available":"Unavailable"],["File storage",health.fileStorage?"Available":"Unavailable"],["Open issues",health.openIssues],["Pilot reports",health.pilotReports],["Pending workflows",health.pendingWork]].map(([label,value])=><div key={String(label)} className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Pilot companies</h2><p className="mt-2 text-sm text-slate-500">Pilot companies see only pilot reports in seller search. Normal members never see pilot reports.</p><div className="mt-4 divide-y">{members.map(member=><article key={member.id} className="flex flex-wrap items-center justify-between gap-4 py-4"><div><p className="font-semibold">{member.company_name}</p><p className="text-sm text-slate-500">{member.login_id||"No Member ID"} · {member.report_count} reports</p></div><button disabled={busy} onClick={()=>send({action:"member",memberId:member.id,isPilot:!member.is_pilot})} className={`rounded-lg px-4 py-2 text-sm font-semibold ${member.is_pilot?"bg-amber-100 text-amber-900":"border"}`}>{member.is_pilot?"Remove pilot status":"Mark as pilot"}</button></article>)}</div></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Acceptance checklist</h2><p className="mt-2 text-sm text-slate-500">Record each result as Pass, Fail or Blocked. Failed checks should have a note.</p><div className="mt-4 divide-y">{checks.map(check=><form key={check.id} className="grid gap-3 py-4 md:grid-cols-[1.4fr_.7fr_1.2fr_auto]" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));send({action:"check",id:check.id,...values});}}><div><p className="font-semibold">{check.label}</p><p className="text-sm text-slate-500">{check.area}</p></div><select name="status" defaultValue={check.status} className="h-11 rounded-lg border bg-white px-3"><option value="not_tested">Not tested</option><option value="pass">Pass</option><option value="fail">Fail</option><option value="blocked">Blocked</option></select><input name="notes" defaultValue={check.notes||""} placeholder="Test note" className="h-11 rounded-lg border px-3"/><button disabled={busy} className="h-11 rounded-lg bg-[#15388c] px-4 text-sm font-semibold text-white">Save</button></form>)}</div></section>
 <section className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-semibold">Problem reports</h2><div className="mt-4 divide-y">{issues.length?issues.map(issue=><article key={issue.id} className="py-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{issue.company_name} · {issue.issue_type.replaceAll("_"," ")}</p><p className="mt-1 text-sm text-slate-500">Ticket {issue.id.slice(0,8).toUpperCase()} · {issue.page_url} · {new Date(issue.created_at).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}</p></div><span className="capitalize">{issue.status.replaceAll("_"," ")}</span></div><p className="mt-3 whitespace-pre-wrap">{issue.description}</p>{issue.screenshot_name&&<a href={`/api/pilot-screenshot/${issue.id}`} target="_blank" className="mt-3 inline-block font-semibold text-emerald-800 underline">View screenshot: {issue.screenshot_name}</a>}<form className="mt-4 grid gap-3 md:grid-cols-[.8fr_1.5fr_auto]" onSubmit={event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));send({action:"issue",id:issue.id,...values});}}><select name="status" defaultValue={issue.status} className="h-11 rounded-lg border bg-white px-3"><option value="open">Open</option><option value="in_progress">In progress</option><option value="ready_for_retest">Ready for retest</option><option value="closed">Closed</option></select><input name="notes" defaultValue={issue.admin_notes||""} placeholder="Member-visible administrator note" className="h-11 rounded-lg border px-3"/><button disabled={busy} className="rounded-lg bg-emerald-800 px-4 text-white">Update</button></form></article>):<p className="py-4 text-slate-500">No problems reported.</p>}</div></section>
 <section className="rounded-2xl border border-rose-200 bg-rose-50 p-6"><h2 className="text-xl font-semibold text-rose-900">Remove pilot data</h2><p className="mt-2 text-sm text-rose-800">Preview the exact scope first. This removes reports, documents, tickets and memberships marked as pilot; it does not touch live member data.</p><button disabled={busy} onClick={()=>send({action:"purge_preview"})} className="mt-4 rounded-lg border border-rose-300 bg-white px-4 py-2 font-semibold text-rose-800">Preview removal</button>{preview&&<div className="mt-4 rounded-xl bg-white p-4"><p className="font-semibold">Preview: {preview.members} members, {preview.reports} reports, {preview.documents} report documents and {preview.issues} tickets.</p><button disabled={busy} onClick={()=>{if(confirm("Permanently remove only the pilot data shown in this preview?"))send({action:"purge",confirm:"REMOVE PILOT DATA"});}} className="mt-3 rounded-lg bg-rose-700 px-4 py-2 font-semibold text-white">Confirm pilot-data removal</button></div>}</section></div>}
