"use client";
import { useRef, useState } from "react";
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { LocationFields } from "@/components/location-fields";

export type EditableReport = { id:string; status:string; gstin:string; firm_name:string; taluka:string; district:string; state:string; pincode?:string; rating:number; dispute:number; amount_paise:number|null; dispute_type:string|null; dispute_other:string|null; dispute_start_month:string|null; dispute_end_month:string|null; dispute_ongoing:number; legal:number; case_number:string|null; summary:string; documents?:{id:string;name:string}[] };
type SellerIdentity={seller_id:string;firm_name:string;taluka:string;district:string;state:string;pincode?:string;gstin:string;report_count:number;average_rating:number};
function Choice({name,label,options,value,onChange}:{name:string;label:string;options:[string,string][];value:string;onChange:(value:string)=>void}) { return <div><label htmlFor={name} className="text-sm font-medium">{label}</label><Select name={name} required value={value} onValueChange={onChange}><SelectTrigger id={name} className="mt-2 h-12 w-full text-base"><SelectValue placeholder="Select a value"/></SelectTrigger><SelectContent>{options.map(([id,text])=><SelectItem value={id} key={id}>{text}</SelectItem>)}</SelectContent></Select></div>; }
function Field({name,label,defaultValue,...props}:{name:string;label:string;defaultValue?:string|number}&React.InputHTMLAttributes<HTMLInputElement>) { return <label className="block text-sm font-medium">{label} *<input name={name} required defaultValue={defaultValue} className={`mt-2 h-12 w-full rounded-lg border border-slate-300 px-3 text-base ${props.readOnly?"bg-slate-100 text-slate-600":"bg-white"}`} maxLength={200} {...props}/></label>; }

export function ReportForm({initial}:{initial?:EditableReport}) {
 const [dispute,setDispute]=useState(Boolean(initial?.dispute)),[legal,setLegal]=useState(Boolean(initial?.legal)),[ongoing,setOngoing]=useState(Boolean(initial?.dispute_ongoing));
 const [rating,setRating]=useState(initial ? String(initial.rating) : ""),[unit,setUnit]=useState("lakhs"),[type,setType]=useState(initial?.dispute_type||"payment_default");
 const [kept,setKept]=useState<string[]>(initial?.documents?.map(document=>document.id)||[]);
 const [seller,setSeller]=useState<SellerIdentity|null>(null),[checkedGstin,setCheckedGstin]=useState(""),[checkingSeller,setCheckingSeller]=useState(false),[requestCorrection,setRequestCorrection]=useState(false);
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[success,setSuccess]=useState(false),[revision,setRevision]=useState(false);
 const requestId=useRef<string|null>(null);
 if(success)return <section className="rounded-2xl border border-emerald-200 bg-white p-8"><h2 className="text-2xl font-semibold">{revision?"Changes sent for admin approval":"Report saved"}</h2><p className="mt-3 text-slate-600">{revision?"The current approved report remains searchable until the admin approves this revision.":"This pending report remains hidden until admin approval."}</p><a href="/member/reports" className="mt-5 inline-block font-semibold text-emerald-800 underline">Return to my reports</a></section>;
 return <form className="space-y-8 rounded-2xl border border-slate-200 bg-white p-5 sm:p-8" onSubmit={async event=>{
  event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget);const files=form.getAll("documents").filter((item):item is File=>item instanceof File&&item.size>0);if(files.length>3||files.some(file=>file.size>1.5*1024*1024)){setError("Upload at most three files, and keep each file at 1.5 MB or smaller.");setBusy(false);return;}requestId.current ||= crypto.randomUUID();const get=(key:string)=>String(form.get(key)||"");
  const report={requestId:requestId.current,gstin:get("gstin"),firmName:get("firmName"),taluka:get("taluka"),district:get("district"),state:get("state"),pincode:get("pincode"),rating:Number(rating),dispute,amount:get("amount"),unit,disputeType:type,disputeOther:get("disputeOther"),disputeStartMonth:get("disputeStartMonth"),disputeEndMonth:get("disputeEndMonth"),disputeOngoing:ongoing,requestSellerCorrection:requestCorrection,legal,caseNumber:get("caseNumber"),summary:get("summary")};
  const payload=new FormData();payload.set("report",JSON.stringify(report));if(initial){payload.set("sourceId",initial.id);payload.set("keepDocuments",JSON.stringify(kept));}form.getAll("documents").forEach(file=>{if(file instanceof File&&file.size)payload.append("documents",file);});
  try{const response=await fetch(initial?"/api/report-edit":"/api/reports",{method:"POST",body:payload});const contentType=response.headers.get("content-type")||"";if(!contentType.includes("application/json")){if(response.status===401||response.status===403||response.redirected)throw new Error("Your secure site session has expired. Refresh the page, sign in again if asked, and then retry.");if(response.status===413)throw new Error("The upload was too large. Keep each document at 1.5 MB or smaller.");throw new Error("The server could not complete this submission. Your form is still here; please retry once.");}const data=await response.json() as {error?:string;revision?:boolean};if(!response.ok)throw new Error(data.error||"Unable to save this report.");setRevision(Boolean(data.revision));setSuccess(true);}catch(cause){setError(cause instanceof Error?cause.message:"Unable to save. Please retry.");}finally{setBusy(false);}
 }}><nav aria-label="Report sections" className="mb-7 rounded-2xl border border-blue-100 bg-blue-50/70 p-4"><p className="text-sm font-semibold text-[#15388c]">Complete the report in six short sections</p><div className="mt-3 flex flex-wrap gap-2">{["Seller","Location","Rating","Dispute","Summary","Documents"].map((label,index)=><a key={label} href={`#report-step-${index+1}`} className="rounded-full border border-blue-200 bg-white px-3 py-1.5 text-sm font-medium text-[#15388c]">{index+1}. {label}</a>)}</div><p className="mt-3 text-sm text-slate-600">Supporting documents are optional. Your entries stay on this page if a validation message appears.</p></nav><fieldset disabled={busy} className="space-y-8 disabled:opacity-70">
  {initial&&<div className="rounded-xl bg-amber-50 p-4 text-sm text-amber-900">{initial.status==="approved"?"Saving creates a pending revision. The approved report stays unchanged until admin approval.":"You are editing your pending report directly."}</div>}
  <section id="report-step-1" className="scroll-mt-24 space-y-5"><h2 className="text-xl font-semibold">1. Seller identity</h2><label className="block text-sm font-medium">Seller GSTIN *<input name="gstin" required minLength={15} maxLength={15} autoComplete="off" readOnly={!!initial} defaultValue={initial?.gstin} className={`mt-2 h-12 w-full rounded-lg border border-slate-300 px-3 text-base ${initial?"bg-slate-100 text-slate-600":"bg-white"}`} onChange={event=>{if(event.target.value.toUpperCase()!==checkedGstin){setSeller(null);setRequestCorrection(false);}}} onBlur={initial?undefined:async event=>{const gstin=event.currentTarget.value.trim().toUpperCase();if(!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(gstin)||gstin===checkedGstin)return;setCheckingSeller(true);setCheckedGstin(gstin);try{const response=await fetch("/api/seller-search",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:gstin})});const data=await response.json() as {seller?:SellerIdentity|null};if(response.ok)setSeller(data.seller||null);}finally{setCheckingSeller(false);}}}/></label><p className="text-sm text-slate-500">{initial?`GSTIN is permanently locked after submission and ends in ${initial.gstin.slice(-4)}.`:checkingSeller?"Checking for an existing seller…":seller?"This seller already exists. Its approved identity is reused below; add only your company’s experience.":"For privacy, enter the complete GSTIN."}</p>{seller&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="font-semibold text-emerald-950">Existing seller found · {seller.report_count} approved report(s) · Average {seller.average_rating}/10</p><p className="mt-1 text-sm text-emerald-900">{seller.firm_name} · {seller.taluka}, {seller.district}, {seller.state}</p><label className="mt-4 flex items-center gap-3 text-sm font-medium"><Checkbox checked={requestCorrection} onCheckedChange={value=>setRequestCorrection(value===true)}/>Request correction to the seller’s identity details</label></div>}<Field name="firmName" label="Firm name" readOnly={!!initial||!!seller&&!requestCorrection} defaultValue={seller?.firm_name||initial?.firm_name}/></section>
  <section id="report-step-2" className="scroll-mt-24"><h2 className="mb-5 text-xl font-semibold">2. Operating location</h2><div key={seller&&!requestCorrection?`${seller.seller_id}-location`:"editable-location"} className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><LocationFields defaultState={seller?.state||initial?.state} defaultDistrict={seller?.district||initial?.district} defaultPincode={seller?.pincode||initial?.pincode} readOnly={!!initial||!!seller&&!requestCorrection}/><Field name="taluka" label="Taluka / Tehsil" readOnly={!!initial||!!seller&&!requestCorrection} maxLength={100} defaultValue={seller?.taluka||initial?.taluka}/></div>{initial?<p className="mt-3 text-sm text-slate-500">Seller identity is locked. This revision can change only your commercial experience and supporting documents.</p>:seller&&!requestCorrection&&<p className="mt-3 text-sm text-slate-500">Seller identity is taken from the approved profile and will not be duplicated or changed by this report.</p>}</section>
  <section id="report-step-3" className="scroll-mt-24"><h2 className="mb-5 text-xl font-semibold">3. Commercial experience</h2><Choice name="rating" label="Experience rating (0–10) *" options={Array.from({length:11},(_,index)=>[String(index),`${index} / 10`])} value={rating} onChange={setRating}/></section>
  <section id="report-step-4" className="scroll-mt-24 space-y-5"><h2 className="text-xl font-semibold">4. Commercial disputes and legal filings</h2><label className="flex items-center gap-3 rounded-xl border p-4"><Checkbox checked={dispute} onCheckedChange={value=>setDispute(value===true)}/>Commercial Dispute Exists</label>{dispute&&<div className="space-y-5 rounded-xl border border-rose-200 bg-rose-50 p-5"><div className="grid gap-5 sm:grid-cols-2"><Field name="amount" label="Disputed amount" type="number" min="0.01" step="0.01" defaultValue={initial?.amount_paise?initial.amount_paise/10000000:undefined}/><Choice name="unit" label="Denomination (INR) *" options={[["thousands","Thousands"],["lakhs","Lakhs"],["crores","Crores"]]} value={unit} onChange={setUnit}/></div><Choice name="disputeType" label="Type of dispute *" options={[["payment_default","Payment default"],["agreement_breach","Agreement breach"],["misrepresentation","Misrepresentation"],["other","Other"]]} value={type} onChange={setType}/>{type==="other"&&<Field name="disputeOther" label="Please specify" maxLength={1000} defaultValue={initial?.dispute_other||""}/>}<div className="grid gap-5 sm:grid-cols-2"><Field name="disputeStartMonth" label="Dispute started (month/year)" type="month" max={new Date().toISOString().slice(0,7)} defaultValue={initial?.dispute_start_month||""}/>{!ongoing&&<Field name="disputeEndMonth" label="Dispute ended (month/year)" type="month" max={new Date().toISOString().slice(0,7)} defaultValue={initial?.dispute_end_month||""}/>}</div><label className="flex items-center gap-3 rounded-lg bg-white/70 p-3"><Checkbox checked={ongoing} onCheckedChange={value=>setOngoing(value===true)}/>This dispute is ongoing</label></div>}<label className="flex items-center gap-3 rounded-xl border p-4"><Checkbox checked={legal} onCheckedChange={value=>setLegal(value===true)}/>Legal Proceedings Initiated</label>{legal&&<div className="rounded-xl border border-violet-200 bg-violet-50 p-5"><Field name="caseNumber" label="Case / filing number" defaultValue={initial?.case_number||""}/></div>}</section>
  <section id="report-step-5" className="scroll-mt-24"><h2 className="mb-3 text-xl font-semibold">5. Factual business summary</h2><label className="text-sm font-medium">Business summary *<textarea name="summary" required minLength={20} maxLength={5000} rows={6} defaultValue={initial?.summary} className="mt-2 w-full rounded-lg border border-slate-300 p-3 text-base"/></label></section>
  <section id="report-step-6" className="scroll-mt-24"><h2 className="mb-3 text-xl font-semibold">6. Supporting documents</h2>{initial?.documents?.map(document=><label key={document.id} className="mb-3 flex items-center gap-3 text-sm"><Checkbox checked={kept.includes(document.id)} onCheckedChange={value=>setKept(current=>value===true?[...current,document.id]:current.filter(id=>id!==document.id))}/><span className="break-all">Keep {document.name}</span></label>)}<p className="mb-4 text-sm text-slate-500">Uncheck a document to remove it from this version. Upload replacement PDF, JPG or PNG files; maximum three documents total and 1.5 MB each.</p><input aria-label="New supporting documents" name="documents" type="file" multiple accept=".pdf,.jpg,.jpeg,.png" className="w-full rounded-lg border border-dashed border-slate-300 p-5 text-sm"/></section>
  {error&&<p role="alert" className="rounded-lg bg-rose-50 p-4 text-rose-700">{error}</p>}<div className="flex flex-wrap gap-3"><Button type="submit" disabled={busy} className="h-12 px-6">{busy?"Saving…":initial?.status==="approved"?"Send changes for approval":initial?"Save pending report":"Submit for admin approval"}</Button><a href={initial?"/member/reports":"/member"} className="inline-flex h-12 items-center rounded-lg border border-slate-300 px-6 text-sm font-semibold text-slate-700">Cancel</a></div>
 </fieldset></form>;
}
