import { ReportReview } from "./report-review";

export type ReportView = {
  id:string; seller_id:string; revision_of:string|null; category:string; reporter_login_id?:string;
  reporter_company?:string; reporter_mobile?:string; firm_name:string; taluka:string;
  district:string; state:string; pincode?:string; rating:number; dispute:number; amount_paise:number|null; dispute_type:string|null;
  dispute_other:string|null; dispute_start_month:string|null; dispute_end_month:string|null; dispute_ongoing:number; legal:number; case_number:string|null; summary:string; status:string;
  review_notes:string|null; created_at:number; gstin:string; dispute_resolved:number; resolved_on:string|null;
  resolution_summary:string|null; pending_resolution:number; identity_change_requested?:number; latest_resolution_status?:string|null; latest_resolution_notes?:string|null; documents?:{id:string;name:string}[]; resolution_requests?:{id:string;resolved_on:string;resolved_amount_paise?:number;description:string;status:string;admin_notes:string|null;created_at:number;documents:{id:string;name:string}[]}[];
  resolved_amount_paise?:number; identity_checked?:number; report_reviewed?:number; evidence_reviewed?:number; approved_for_display?:number; reviewed_at?:number|null;
};

export function ReportCards({reports,admin=false,memberActions=false,experienceOnly=false}:{reports:ReportView[];admin?:boolean;memberActions?:boolean;experienceOnly?:boolean}) {
 return <div className="space-y-5">{reports.map(report => <article key={report.id} className={`rounded-[12px] border border-slate-300/70 p-5 sm:p-7 ${experienceOnly?"bg-white/58 shadow-sm":"bg-white"}`}>
  <div className="flex flex-wrap items-start justify-between gap-3"><div>{!experienceOnly&&<><h2 className="text-xl font-semibold">{report.firm_name}</h2><p className="mt-1 text-sm text-slate-500">{report.taluka}, {report.district}, {report.state}{report.pincode?` · PIN ${report.pincode}`:""}</p></>}{experienceOnly&&!!report.dispute&&report.reporter_company&&<><p className="text-sm font-semibold text-rose-700">Dispute reported by</p><h2 className="mt-1 text-lg font-semibold">{report.reporter_company}</h2></>}{admin&&<div className="mt-2 text-sm"><p className="font-semibold capitalize text-emerald-800">Category: {report.category}</p><p className="mt-1 text-slate-600">Submitted by {report.reporter_company} · {report.reporter_login_id || "Member ID pending"} · {report.reporter_mobile}</p></div>}</div><span className="rounded-full bg-emerald-50 px-3 py-2 text-sm font-semibold capitalize text-emerald-800">{report.status} · {report.rating}/10</span></div>
  {!experienceOnly&&<dl className="mt-5 text-sm"><dt className="text-slate-500">GSTIN</dt><dd className="mt-1 font-mono">{report.gstin}</dd></dl>}{admin&&report.status==="pending"&&!!report.identity_change_requested&&<p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-amber-900">Seller identity correction requested. Compare these details with the approved seller record before deciding.</p>}<p className="mt-5 whitespace-pre-wrap break-words leading-7">{report.summary}</p>
  {!!Number(report.dispute)&&<div className={`mt-4 rounded-xl p-4 text-sm ${report.dispute_resolved?'bg-emerald-50 text-emerald-900':'bg-rose-50 text-rose-900'}`}><div className="flex flex-wrap items-center justify-between gap-2"><strong>Reported commercial dispute</strong><span className="rounded-full bg-white/70 px-3 py-1 font-semibold">{report.dispute_resolved?'Resolved':'Open'}</span></div><p className="mt-2">{report.dispute_type?.replaceAll("_"," ")}{report.dispute_other?` — ${report.dispute_other}`:""} · {new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format((Number(report.amount_paise)||0)/100)}</p><p className="mt-2"><strong>Dispute period:</strong> {report.dispute_start_month?`${monthLabel(report.dispute_start_month)} – ${report.dispute_ongoing?'Ongoing':report.dispute_end_month?monthLabel(report.dispute_end_month):'Not provided'}`:'Not provided'}</p>{report.resolved_amount_paise? <p className="mt-2"><strong>Resolved amount:</strong> {new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(report.resolved_amount_paise/100)}</p>:null}{report.dispute_resolved&&report.resolved_on&&<><p className="mt-2">Resolved on {safeDate(report.resolved_on)}</p><p className="mt-1 whitespace-pre-wrap">{report.resolution_summary}</p></>}</div>}
  {!!Number(report.legal)&&<p className="mt-4 rounded-xl bg-violet-50 p-4 text-sm text-violet-900">Legal proceedings reported · Case / filing: {report.case_number}</p>}
  <div className="mt-4 flex flex-wrap gap-2">{report.report_reviewed? <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-800">Admin reviewed</span>:null}{report.identity_checked? <span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-semibold text-emerald-800">Seller identity checked</span>:null}{report.evidence_reviewed? <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-800">Evidence reviewed</span>:null}</div><p className="mt-4 text-sm text-slate-500">Reported {safeDate(report.created_at)} · Member-submitted information</p>
  {memberActions&&["pending","approved"].includes(report.status)&&<div className="mt-4 flex flex-wrap gap-3">{(report.status==='pending'||!report.pending_resolution)&&<a href={`/member/reports/${report.id}/edit`} className="inline-block rounded-lg border px-4 py-2 text-sm font-semibold text-emerald-800">{report.status==="approved"?"Request changes":"Edit pending report"}</a>}{report.status==='approved'&&!!report.dispute&&!report.dispute_resolved&&!report.pending_resolution&&<a href={`/member/reports/${report.id}/resolve`} className="inline-block rounded-lg bg-emerald-800 px-4 py-2 text-sm font-semibold text-white">Mark dispute resolved</a>}{!!report.pending_resolution&&<span className="rounded-lg bg-amber-50 px-4 py-2 text-sm font-semibold text-amber-800">Resolution awaiting admin review</span>}</div>}
  {memberActions&&report.latest_resolution_status==='rejected'&&<p className="mt-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">Resolution request rejected{report.latest_resolution_notes?`: ${report.latest_resolution_notes}`:"."}</p>}
  {memberActions&&report.resolution_requests?.length?<details className="mt-4 rounded-lg border p-4"><summary className="cursor-pointer text-sm font-semibold text-emerald-800">Resolution request history ({report.resolution_requests.length})</summary><div className="mt-4 space-y-4">{report.resolution_requests.map(request=><div key={request.id} className="border-t pt-3 text-sm first:border-0 first:pt-0"><div className="flex flex-wrap justify-between gap-2"><strong>Resolution date: {new Date(`${request.resolved_on}T00:00:00`).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}</strong><span className="font-semibold capitalize">{request.status}</span></div>{request.resolved_amount_paise?<p className="mt-2 font-medium">Amount: {new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(request.resolved_amount_paise/100)}</p>:null}<p className="mt-2 whitespace-pre-wrap text-slate-600">{request.description}</p>{request.admin_notes&&<p className="mt-2 text-slate-600">Admin note: {request.admin_notes}</p>}{request.documents.map(document=><a key={document.id} href={`/api/resolution-document/${document.id}`} className="mt-2 block break-all font-medium text-emerald-800 underline">{document.name}</a>)}</div>)}</div></details>:null}
  {report.review_notes&&<p className="mt-3 text-sm text-slate-600">Review note: {report.review_notes}</p>}
  {report.documents?.length?<div className="mt-4 flex flex-wrap gap-4">{report.documents.map(document=><a key={document.id} href={`/api/report-document/${document.id}`} className="break-all text-sm font-medium text-emerald-800 underline">{document.name}</a>)}</div>:null}
  {admin&&report.status==="pending"&&<ReportReview id={report.id} hasDocuments={Boolean(report.documents?.length)}/>}</article>)}</div>;
}

function monthLabel(value:string){
  const match=String(value||"").match(/^(\d{4})-(\d{2})$/);
  if(!match)return "Not provided";
  const date=new Date(Date.UTC(Number(match[1]),Number(match[2])-1,1));
  if(Number.isNaN(date.valueOf()))return "Not provided";
  return new Intl.DateTimeFormat("en-IN",{month:"short",year:"numeric",timeZone:"UTC"}).format(date);
}
function safeDate(value:string|number|Date|null|undefined){
  if(value==null||value==="")return "—";
  const date=value instanceof Date?value:typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value)?new Date(`${value}T00:00:00`):new Date(value);
  if(Number.isNaN(date.valueOf()))return "—";
  return date.toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"});
}
