"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import states from "@/lib/data/state-districts.json";
import type { SeedRequest } from "@/lib/seed-requests";
const locations = states as Record<string, string[]>;
const names = Object.keys(locations);
const input = "w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-900";
const label = "block space-y-1 text-sm font-medium text-slate-700";
type Values = Omit<SeedRequest, "id" | "ownerId" | "ownerCompany" | "status" | "createdAt" | "updatedAt" | "publishedAt" | "closedAt" | "quotationDeadline"> & { quotationDeadline: string };
const initial: Values = { crop: "", segment: "", description: "", varietyType: "hybrid", productMatch: "exact", quantity: 0, quantityUnit: "kg", partialAllowed: false, cleaning: "either", treatment: "either", germinationRequired: false, gotRequired: false, deliveryState: "", deliveryDistrict: "", destination: "", deliveryBy: "", transport: "negotiable", paymentTerms: "", quotationDeadline: "", anonymous: false, panIndia: false, supplierStates: [] };
export function SeedRequestForm() {
  const [values, setValues] = useState<Values>(initial); const [review, setReview] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const router = useRouter();
  function set<K extends keyof Values>(key: K, value: Values[K]) { setValues(current => ({ ...current, [key]: value })); setError(""); }
  async function publish() {
    setBusy(true); setError(""); try { const response = await fetch("/api/member/seed-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); router.push(`/member/buy-sell/${result.request.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to publish."); } finally { setBusy(false); }
  }
  const select = <K extends keyof Values>(key: K, options: [string, string][]) => <select className={input} value={String(values[key])} onChange={e => set(key, e.target.value as Values[K])}>{options.map(([v, text]) => <option key={v} value={v}>{text}</option>)}</select>;
  const yesNo = <K extends keyof Values>(key: K) => <select className={input} value={String(values[key])} onChange={e => set(key, (e.target.value === "true") as Values[K])}><option value="false">No</option><option value="true">Yes</option></select>;
  if (review) return <section className="space-y-4 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">Review before publishing</h2><p className="text-sm text-slate-600">This request will be published immediately. Buyer identity: <strong>{values.anonymous ? "Anonymous to suppliers" : "Company name visible"}</strong>.</p><dl className="grid gap-3 text-sm sm:grid-cols-2">{Object.entries(values).map(([key, value]) => <div key={key} className="border-b pb-2"><dt className="text-slate-500">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="break-words font-medium">{Array.isArray(value) ? value.join(", ") || "None" : typeof value === "boolean" ? value ? "Yes" : "No" : String(value || "—")}</dd></div>)}</dl><div className="flex gap-3"><button className="rounded-lg border px-4 py-2" onClick={() => setReview(false)}>Edit details</button><button disabled={busy} className="rounded-lg bg-[#15388c] px-4 py-2 text-white disabled:opacity-50" onClick={publish}>{busy ? "Publishing…" : "Publish request"}</button></div><p role="alert" className="text-sm text-red-700">{error}</p></section>;
  return <form onSubmit={e => { e.preventDefault(); setReview(true); }} className="space-y-6 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">New Seed buying request</h2>
    <div className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-blue-200 bg-blue-50 p-4"><div><p className="font-semibold text-slate-900">Post as anonymous buyer</p><p className="text-sm text-slate-600">When on, suppliers see “Anonymous buyer” unless you reveal your company name to one of them later.</p><p className="text-sm font-medium text-[#15388c]">{values.anonymous ? "On — company name hidden" : "Off — company name visible"}</p></div><button type="button" role="switch" aria-checked={values.anonymous} aria-label="Post as anonymous buyer" onClick={() => set("anonymous", !values.anonymous)} className={`rounded-full px-5 py-2.5 font-semibold ${values.anonymous ? "bg-[#15388c] text-white" : "border border-slate-300 bg-white text-slate-800"}`}>{values.anonymous ? "Anonymous ON" : "Anonymous OFF"}</button></div>
    <fieldset className="grid gap-4 md:grid-cols-2"><legend className="mb-3 font-semibold">Product</legend><label className={label}>Crop<input required maxLength={80} className={input} value={values.crop} onChange={e => set("crop", e.target.value)} /></label><label className={label}>Segment<input required maxLength={80} className={input} value={values.segment} onChange={e => set("segment", e.target.value)} /></label><label className={`${label} md:col-span-2`}>Product or variety description<textarea required maxLength={1200} className={input} value={values.description} onChange={e => set("description", e.target.value)} /></label><label className={label}>Type{select("varietyType", [["hybrid", "Hybrid"], ["research", "Research/Variety"]])}</label><label className={label}>Product match{select("productMatch", [["exact", "Exact product required"], ["equivalent", "Equivalent accepted"]])}</label></fieldset>
    <fieldset className="grid gap-4 md:grid-cols-2"><legend className="mb-3 font-semibold">Quantity and quality</legend><label className={label}>Required quantity<input required type="number" min="0.001" step="any" className={input} value={values.quantity || ""} onChange={e => set("quantity", Number(e.target.value))} /></label><label className={label}>Unit{select("quantityUnit", [["kg", "kg"], ["MT", "MT"]])}</label><label className={label}>Accept partial offers?{yesNo("partialAllowed")}</label><label className={label}>Clean or raw{select("cleaning", [["either", "Either"], ["clean", "Clean"], ["raw", "Raw"]])}</label><label className={label}>Treated or untreated{select("treatment", [["either", "Either"], ["treated", "Treated"], ["untreated", "Untreated"]])}</label><label className={label}>Germination report required?{yesNo("germinationRequired")}</label><label className={label}>GOT report required?{yesNo("gotRequired")}</label></fieldset>
    <fieldset className="grid gap-4 md:grid-cols-2"><legend className="mb-3 font-semibold">Delivery and commercial terms</legend><label className={label}>Delivery state<select required className={input} value={values.deliveryState} onChange={e => setValues(v => ({ ...v, deliveryState: e.target.value, deliveryDistrict: "" }))}><option value="">Select state</option>{names.map(v => <option key={v}>{v}</option>)}</select></label><label className={label}>Delivery district<select required className={input} value={values.deliveryDistrict} onChange={e => set("deliveryDistrict", e.target.value)}><option value="">Select district</option>{(locations[values.deliveryState] || []).map(v => <option key={v}>{v}</option>)}</select></label><label className={label}>Destination / delivery address<input required maxLength={240} className={input} value={values.destination} onChange={e => set("destination", e.target.value)} /></label><label className={label}>Required delivery date<input required type="date" className={input} value={values.deliveryBy} onChange={e => set("deliveryBy", e.target.value)} /></label><label className={label}>Transportation{select("transport", [["negotiable", "Negotiable"], ["included", "Included"], ["excluded", "Excluded"]])}</label><label className={label}>Preferred payment terms (optional)<input maxLength={400} className={input} value={values.paymentTerms} onChange={e => set("paymentTerms", e.target.value)} /></label><label className={label}>Final quotation date and time (IST)<input required type="datetime-local" className={input} value={values.quotationDeadline} onChange={e => set("quotationDeadline", e.target.value)} /></label></fieldset>
    <fieldset className="space-y-4"><legend className="font-semibold">Supplier states</legend><label className="flex gap-2 text-sm"><input type="checkbox" checked={values.panIndia} onChange={e => set("panIndia", e.target.checked)} /> Pan India (all approved Agriculture members)</label>{!values.panIndia && <div><p className="mb-2 text-sm">Select supplier states</p><div className="grid max-h-52 gap-2 overflow-auto rounded-lg border p-3 sm:grid-cols-3">{names.map(state => <label key={state} className="flex gap-2 text-sm"><input type="checkbox" checked={values.supplierStates.includes(state)} onChange={e => set("supplierStates", e.target.checked ? [...values.supplierStates, state] : values.supplierStates.filter(s => s !== state))} />{state}</label>)}</div></div>}</fieldset>
    <button className="rounded-lg bg-[#15388c] px-5 py-2.5 font-semibold text-white">Review request</button><p role="alert" className="text-sm text-red-700">{error}</p></form>;
}
