import { LegalPage } from "@/components/legal-page";
export default function Terms(){return <LegalPage title="Terms of Use" path="/terms" effective="12 September 2026">
 <section><h2>1. Agreement and eligibility</h2><p>These Terms govern Sellers Trust Network, operated by Meet Patel. The service is presently for authorised representatives aged 18 or older acting for Indian businesses. By registering, the representative confirms authority to bind the business and accepts these Terms and the Privacy Policy.</p></section>
 <section><h2>2. Membership</h2><p>Membership is currently free. Approval is discretionary. The administrator may reject an application without a detailed reason and may suspend or deactivate access for misuse, security risk or breach. Credentials are personal to the authorised member, must not be shared, and the member is responsible for activity performed through its account.</p></section>
 <section><h2>3. Permitted use</h2><p>The platform may be used only for legitimate B2B due diligence and factual commercial reporting. Members must not enumerate GSTINs, scrape data, bypass category controls, impersonate others, disrupt the service, introduce malicious material, or use results for harassment, discrimination or an unlawful purpose.</p></section>
 <section><h2>4. Reports and evidence</h2><p>Members warrant that every submission is factual, lawful, relevant, supported by records and written neutrally. Members must have authority to upload each document and must not include Aadhaar data, passwords, payment-card data or unrelated personal information. By submitting content, the member assigns to the platform, to the extent legally permissible, ownership of the submitted report and grants an irrevocable, worldwide, royalty-free right to store, review, reproduce, adapt for privacy, publish and preserve it for platform purposes. Underlying third-party documents remain subject to their lawful rights.</p></section>
 <section><h2>5. Review, corrections and account closure</h2><p>Nothing becomes searchable until administrator approval. Approval is an administrative moderation decision, not confirmation that every fact is true. Sellers may request correction or removal with a GST certificate at <a className="underline" href="mailto:meetpatel.hmt@gmail.com">meetpatel.hmt@gmail.com</a>. A challenged record may be labelled “under review.” Following account closure, approved historical reports may remain while member-facing reporter attribution is anonymised.</p></section>
 <section><h2>6. No credit or professional advice</h2><p>The platform is one due-diligence input only. It does not provide credit ratings, legal, financial or professional advice; does not guarantee payment, performance, identity or solvency; and does not replace independent verification. Members must make their own commercial decisions and obtain professional advice where appropriate.</p></section>
 <section><h2>7. Intellectual property and availability</h2><p>The platform software, design, compilation and branding belong to Meet Patel or applicable licensors. Access may be changed, interrupted or discontinued for security, maintenance, legal or operational reasons. No uninterrupted or error-free availability is promised.</p></section>
 <section><h2>8. Liability and indemnity</h2><p>To the maximum extent permitted by law, the platform is not liable for indirect, consequential, reputational or lost-profit damages or decisions made from member-submitted information. Aggregate liability is limited to membership fees actually paid by the affected member during the 12 months preceding the claim. Rights and liabilities that cannot lawfully be excluded remain unaffected. The member will indemnify Meet Patel and Sellers Trust Network against claims and costs arising from unlawful, false, defamatory or unauthorised submissions, credential sharing or breach of these Terms.</p></section>
 <section><h2>9. Disputes and governing law</h2><p>Indian law governs these Terms. Parties will first attempt good-faith negotiation or mediation. If unresolved, the dispute will be referred to one mutually appointed arbitrator seated in Himatnagar, Gujarat, under the Arbitration and Conciliation Act, 1996. Proceedings will be in English unless the parties agree to Gujarati or Hindi. Courts at Himatnagar, Gujarat have jurisdiction for matters not subject to arbitration and arbitration-related relief.</p></section>
 <section><h2>10. Changes and contact</h2><p>Material changes will ordinarily be notified 15 days in advance. Continued use after the effective date constitutes acceptance. Questions may be sent to <a className="underline" href="mailto:meetpatel.hmt@gmail.com">meetpatel.hmt@gmail.com</a>.</p></section>
 </LegalPage>;}
