import { readJsonBody } from "@/lib/request-body";
import { NextResponse } from "next/server";
import { currentMember } from "@/lib/member-session";
import { reportDb } from "@/lib/report-store";
import { verifyPassword } from "@/lib/passwords";
import { notifyAdmin } from "@/lib/notifications";
import { consumeLimit } from "@/lib/security";
const reply=(body:object,status=200)=>NextResponse.json(body,{status,headers:{"Cache-Control":"no-store"}});
export async function POST(request:Request){const member=await currentMember();if(!member?.passwordHash||member.mustChangePassword)return reply({error:"Approved membership required."},403);try{const body=await readJsonBody(request) as Record<string,unknown>,action=String(body.action||"request"),db=reportDb();if(action==="cancel"){const result=await db.prepare("UPDATE account_deletion_requests SET status='cancelled',reviewed_at=? WHERE member_id=? AND status='pending'").bind(Date.now(),member.id).run();return result.meta.changes?reply({ok:true}):reply({error:"No pending request found."},409);}const limited=await consumeLimit(request,"account_deletion_password",String(member.id),10,15*60*1000);if(!limited.allowed)return reply({error:"Too many attempts. Please wait 15 minutes."},429);const reason=String(body.reason||"").trim(),password=String(body.password||"");if(reason.length<5||reason.length>1000||!verifyPassword(password,member.passwordHash))return reply({error:"Enter your current password and a reason."},400);if(await db.prepare("SELECT id FROM account_deletion_requests WHERE member_id=? AND status='pending'").bind(member.id).first())return reply({error:"A deletion request is already pending."},409);const id=crypto.randomUUID();await db.prepare("INSERT INTO account_deletion_requests(id,member_id,reason,status,created_at) VALUES(?,?,?,'pending',?)").bind(id,member.id,reason,Date.now()).run();await notifyAdmin({type:"account_deletion_request",title:"Account-deletion request",message:`${member.companyName} requested account deletion.`,href:"/admin/governance"});return reply({id},201);}catch{return reply({error:"Unable to save the deletion request."},500);}}
