import { redirect } from "next/navigation";
import { requireChatGPTUser } from "@/app/chatgpt-auth";
import { isConfiguredAdmin } from "@/lib/member-data";
import { actionLabel,auditEntries } from "@/lib/admin-dashboard";
import { ReportShell } from "@/components/report-shell";
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;action?:string;from?:string;to?:string}>}){const user=await requireChatGPTUser("/admin/audit");if(!isConfiguredAdmin(user.email))redirect("/join");const params=await searchParams,q=String(params.q||"").trim().toLowerCase(),action=String(params.action||""),from=/^\d{4}-\d{2}-\d{2}$/.test(String(params.from||""))?new Date(`${params.from}T00:00:00Z`).valueOf():0,to=/^\d{4}-\d{2}-\d{2}$/.test(String(params.to||""))?new Date(`${params.to}T23:59:59.999Z`).valueOf():Number.MAX_SAFE_INTEGER;const all=await auditEntries(),actions=[...new Set(all.map(entry=>entry.action))].sort(),entries=all.filter(entry=>(!q||`${entry.source} ${entry.actor} ${entry.subject} ${entry.details||""} ${actionLabel(entry.action)}`.toLowerCase().includes(q))&&(!action||entry.action===action)&&entry.created_at>=from&&entry.created_at<=to);
 return <ReportShell admin title="Audit trail" description="Read-only history of membership, credential, seller-report and dispute-resolution activity."><form method="get" className="grid gap-4 rounded-2xl border bg-white p-5 md:grid-cols-4"><label className="text-sm font-medium md:col-span-2">Member, company or record<input name="q" defaultValue={params.q} className="mt-2 h-11 w-full rounded-lg border px-3 text-base"/></label><label className="text-sm font-medium">Action<select name="action" defaultValue={action} className="mt-2 h-11 w-full rounded-lg border bg-white px-3 text-base"><option value="">All actions</option>{actions.map(value=><option key={value} value={value}>{actionLabel(value)}</option>)}</select></label><div className="flex items-end gap-2"><button className="h-11 rounded-lg bg-[#15388c] px-5 text-sm font-semibold text-white">Filter</button><a href="/admin/audit" className="h-11 rounded-lg border px-4 py-3 text-sm font-semibold">Clear</a></div><label className="text-sm font-medium">From date<input name="from" type="date" defaultValue={params.from} className="mt-2 h-11 w-full rounded-lg border px-3 text-base"/></label><label className="text-sm font-medium">To date<input name="to" type="date" defaultValue={params.to} className="mt-2 h-11 w-full rounded-lg border px-3 text-base"/></label></form><p className="my-5 text-sm text-slate-600">{entries.length} matching event(s) from the latest {all.length} records.</p><div className="overflow-hidden rounded-2xl border bg-white">{entries.length?entries.map((entry,index)=><article key={`${entry.source}-${entry.created_at}-${index}`} className="grid gap-2 border-b p-5 last:border-0 md:grid-cols-[1.4fr_1fr_auto]"><div><p className="font-semibold">{actionLabel(entry.action)}</p><p className="mt-1 text-sm text-slate-600">{entry.subject}{entry.details?` · ${entry.details}`:""}</p></div><div className="text-sm"><p>{entry.actor}</p><p className="mt-1 capitalize text-slate-500">{entry.source}</p></div><time className="text-sm text-slate-500">{new Date(entry.created_at).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}</time></article>):<p className="p-7 text-slate-600">No audit events match these filters.</p>}</div></ReportShell>;
}
