import { readJsonBody } from "@/lib/request-body";
import { NextResponse } from "next/server";
import { reportDb,reportMember,identifierKey,safeReportColumns,maskReport } from "@/lib/report-store";
import { syncApprovedResolutionsToReports } from "@/lib/sync-approved-resolutions";
export async function POST(request:Request){
 const reply=(data:object,status=200)=>NextResponse.json(data,{status,headers:{"Cache-Control":"no-store"}});
 const member=await reportMember();if(!member)return reply({error:"An approved membership and assigned category are required."},403);
 try{
  await syncApprovedResolutionsToReports();
  const body=await readJsonBody(request) as {query?:string},query=String(body.query||"").trim().toUpperCase();if(!/^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][1-9A-Z]Z[0-9A-Z]$/.test(query))return reply({error:"Enter the complete valid GSTIN."},400);
  const key=identifierKey(member.category,"gst",query),db=reportDb();
  if(!member.searchEnabled)return reply({error:"Seller search has been disabled for your membership. Contact the administrator."},403);
  const searchDate=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kolkata",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  const existing=await db.prepare("SELECT id FROM member_searches WHERE member_id=? AND search_date=? AND gst_lookup=?").bind(member.id,searchDate,key).first();
  if(!existing){await db.prepare("INSERT INTO member_searches(id,member_id,search_date,gst_lookup,created_at) SELECT ?,?,?,?,? WHERE (SELECT count(*) FROM member_searches WHERE member_id=? AND search_date=?)<30 ON CONFLICT (member_id,search_date,gst_lookup) DO NOTHING").bind(crypto.randomUUID(),member.id,searchDate,key,Date.now(),member.id,searchDate).run();if(!await db.prepare("SELECT id FROM member_searches WHERE member_id=? AND search_date=? AND gst_lookup=?").bind(member.id,searchDate,key).first())return reply({error:"Your daily limit of 30 different GSTIN searches has been reached. It resets at midnight IST."},429);}
  const [result,identity,totals,review]=await Promise.all([
   db.prepare(`SELECT ${safeReportColumns},CASE WHEN r.dispute=1 AND EXISTS(SELECT 1 FROM account_deletion_requests q WHERE q.member_id=r.member_id AND q.status='approved') THEN 'Former network member' WHEN r.dispute=1 THEN m.company_name ELSE NULL END reporter_company FROM seller_reports r JOIN sellers s ON s.id=r.seller_id JOIN members m ON m.id=r.member_id WHERE r.category=? AND s.category=? AND r.status='approved' AND s.gst_lookup=? AND m.is_pilot=? ORDER BY r.created_at DESC LIMIT 101`).bind(member.category,member.category,key,Number(member.isPilot)).all<Record<string,unknown>>(),
   db.prepare("SELECT r.seller_id,r.firm_name,r.taluka,r.district,r.state,r.pincode,s.gst_last4 FROM seller_reports r JOIN sellers s ON s.id=r.seller_id JOIN members m ON m.id=r.member_id WHERE r.category=? AND s.gst_lookup=? AND r.status='approved' AND m.is_pilot=? ORDER BY COALESCE(r.reviewed_at,r.created_at) DESC LIMIT 1").bind(member.category,key,Number(member.isPilot)).first<Record<string,unknown>>(),
   db.prepare("SELECT count(*) report_count,avg(rating) average_rating,count(DISTINCT r.member_id) reporting_companies,sum(CASE WHEN r.dispute=1 THEN 1 ELSE 0 END) disputes,sum(CASE WHEN r.dispute=1 AND r.dispute_resolved=0 THEN 1 ELSE 0 END) open_disputes,sum(CASE WHEN r.dispute=1 AND r.dispute_resolved=1 THEN 1 ELSE 0 END) resolved_disputes,sum(CASE WHEN r.dispute=1 THEN COALESCE(r.amount_paise,0) ELSE 0 END) reported_amount_paise,sum(COALESCE(r.resolved_amount_paise,0)) resolved_amount_paise,sum(CASE WHEN r.legal=1 THEN 1 ELSE 0 END) legal_count,max(COALESCE(r.reviewed_at,r.created_at)) latest_reviewed_at FROM seller_reports r JOIN sellers s ON s.id=r.seller_id JOIN members m ON m.id=r.member_id WHERE r.category=? AND s.gst_lookup=? AND r.status='approved' AND m.is_pilot=?").bind(member.category,key,Number(member.isPilot)).first<Record<string,number>>(),
   db.prepare("SELECT (EXISTS(SELECT 1 FROM seller_reports pending JOIN sellers s ON s.id=pending.seller_id WHERE pending.category=? AND s.gst_lookup=? AND pending.status='pending' AND EXISTS(SELECT 1 FROM seller_reports approved WHERE approved.seller_id=pending.seller_id AND approved.status='approved' AND (approved.firm_name<>pending.firm_name OR approved.taluka<>pending.taluka OR approved.district<>pending.district OR approved.state<>pending.state))) OR EXISTS(SELECT 1 FROM seller_correction_requests c JOIN sellers s ON s.id=c.seller_id WHERE s.category=? AND s.gst_lookup=? AND c.status='pending')) under_review").bind(member.category,key,member.category,key).first<{under_review:number}>(),
  ]);
  const reports=result.results.slice(0,100).map(row=>{const {review_notes,pending_resolution,identity_change_requested,revision_of,...visible}=maskReport(row) as Record<string,unknown>;return visible;});
  return reply({seller:identity?{seller_id:String(identity.seller_id),firm_name:String(identity.firm_name),taluka:String(identity.taluka),district:String(identity.district),state:String(identity.state),pincode:String(identity.pincode||""),gstin:`***********${identity.gst_last4}`,report_count:Number(totals?.report_count||0),average_rating:Math.round(Number(totals?.average_rating||0)*10)/10,reporting_companies:Number(totals?.reporting_companies||0),disputes:Number(totals?.disputes||0),open_disputes:Number(totals?.open_disputes||0),resolved_disputes:Number(totals?.resolved_disputes||0),reported_amount_paise:Number(totals?.reported_amount_paise||0),resolved_amount_paise:Number(totals?.resolved_amount_paise||0),legal_count:Number(totals?.legal_count||0),latest_reviewed_at:Number(totals?.latest_reviewed_at||0),under_review:Boolean(review?.under_review)}:null,reports,more:result.results.length>100});
 }catch{return reply({error:"Search is temporarily unavailable. Please try again."},503);}
}
